channels:
        - defaults
        - conda-forge
dependencies:
        - python
        - numpy
        - pandas
        - xarray
	- netCDF4==1.5.3
        - matplotlib
        - scikit-learn
        - scipy
        - statsmodels
        - cmocean
        - basemap
        - basemap-data-hires
        - spyder
        - notebook
