channels:
        - defaults
        - conda-forge
dependencies:
        - python=3.7
        - numpy=1.16.3
        - matplotlib=3.0.3
        - pandas=0.24.2
        - scikit-learn=0.20.3
        - scipy=1.4.1
        - basemap
        - basemap-data-hires
        - spyder
        - jupyter notebook
