name: calval
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - xarray
  - netcdf4
  - matplotlib
  - scikit-learn
  - scipy
  - statsmodels
  - cmocean
  - notebook
  - cartopy
