channels:
        - defaults
        - conda-forge
dependencies:
        - python
        - numpy
        - pandas
        - matplotlib
        - scikit-learn
        - scipy
        - basemap
        - basemap-data-hires
        - spyder
        - notebook
